spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:farmcollectordb
    driver-class-name: org.h2.Driver
    username: farmuser
    password: farmuser
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

